import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import data from"../data/processed/constitution-india-2026.json"with{type:"json"};
import evaluationCases from"./guidance-evaluation-cases.json"with{type:"json"};
const cases=[["I was arrested and nobody told me why.","22",["arrest","detention","grounds"]],["The government treated me differently because of my religion.","15",["discrimination","religion","state"]],["The government is preventing me from speaking publicly.","19",["speech","expression","right"]],["My child has been denied elementary education.","21A",["education","children","state"]],["I can't afford a lawyer.","39A",["legal","aid","justice"]]];
function search(words){return data.chunks.map(c=>({article:c.article,score:words.filter(w=>(c.heading+" "+c.text).toLowerCase().includes(w)).length})).sort((a,b)=>b.score-a.score).slice(0,8)}
for(const[query,article,words]of cases)test(`retrieves Article ${article}: ${query}`,()=>assert.ok(search(words).some(x=>x.article===article)));
test("does not generate constitutional citations for a statutory gap",()=>{const source=readFileSync(new URL("../lib/ai/guidance.ts",import.meta.url),"utf8");assert.match(source,/"tenancy or contractual dispute"/);assert.match(source,/const supported = statutoryGap \? \[\] : sexualViolence/)});
test("uses issue-specific guidance and follow-up questions",()=>{const source=readFileSync(new URL("../lib/ai/guidance.ts",import.meta.url),"utf8");assert.match(source,/Do you owe the money, or does the other person owe you\?/);assert.match(source,/Is this mainly about rent, eviction, repairs, or return of a security deposit\?/);assert.match(source,/What did you buy, when did you buy it/);assert.doesNotMatch(source,/Which State or Union Territory are you in\?/)});
test("recognises owing and the common owning-money typo as debt language",()=>{const source=readFileSync(new URL("../lib/ai/guidance.ts",import.meta.url),"utf8");assert.match(source,/owing\|owning/)});
test("maintains a 25-scenario legal navigation evaluation set",()=>{assert.equal(evaluationCases.length,25);for(const item of evaluationCases){assert.ok(item.issue.length>12);assert.ok(item.domain)}});
test("structured guidance distinguishes police, lawyer, RTI and formal action",()=>{const source=readFileSync(new URL("../lib/ai/guidance.ts",import.meta.url),"utf8");for(const field of["police_help","lawyer_help","best_next_route","formal_action","escalation_path","evidence_to_preserve","case_state"])assert.match(source,new RegExp(field))});
test("sexual violence retrieves only the verified Article 21 protection",()=>{const source=readFileSync(new URL("../lib/ai/guidance.ts",import.meta.url),"utf8");assert.match(source,/rap\(\?:e\|ed\|ing\)/);assert.match(source,/Article 21 life personal liberty/);assert.match(source,/result\.chunk\.article === "21"/)});
test("all cited core provisions contain their own Article number",()=>{for(const article of["14","15","19","21","21A","22","32","39A"]){const c=data.chunks.find(x=>x.article===article);assert.ok(c,`missing ${article}`);assert.match(c.text,new RegExp(`${article}.`))}});
