import {LegalRetriever} from "@/lib/retrieval/retriever";
import type{Guidance,RelevantLaw,RetrievedChunk}from "@/lib/legal/types";
const retriever=new LegalRetriever();
const emergencyTerms=/\b(immediate danger|attacking|attack|violence|violent|kill|killing|suicide|self[- ]harm|sexual assault|rape|child abuse|threatening me now)\b/i;
const statutory:Record<string,RegExp>={"consumer dispute":/refund|fake product|seller|consumer|defective/,"tenancy or contractual dispute":/landlord|deposit|rent|tenant/,"employment dispute":/employer|salary|wages|fired|workplace/,"private debt or contractual dispute":/owe|loan|money.*return|debt/};
function classify(issue:string){if(/arrest|detain|custody|police station/i.test(issue))return"arrest or detention";if(/discriminat|treated.*different|religion|caste|race/i.test(issue))return"equality or discrimination";if(/speak|speech|criticis|instagram|post/i.test(issue))return"freedom of expression";if(/school|education|child.*denied/i.test(issue))return"education";if(/lawyer|legal aid|afford/i.test(issue))return"access to legal help";for(const[k,r]of Object.entries(statutory))if(r.test(issue))return k;return"legal issue requiring more facts"}
function sentence(text:string){return text.replace(/^\s*(?:\d+\[)?\d+[A-Z]?\.\s*/i,"").split(/(?<=[.!?])\s+/)[0].replace(/\s+/g," ").slice(0,420)}
function isVerified(r:RetrievedChunk){return Boolean(r.chunk.chunkId&&r.chunk.article&&r.chunk.text&&r.chunk.text.includes(r.chunk.article+"."))}
function relevance(score:number):"direct"|"possible"|"contextual"{return score>.32?"direct":score>.18?"possible":"contextual"}
export function generateGuidance(issue:string,debug=false):Guidance{
  const category=classify(issue),emergency=emergencyTerms.test(issue);const retrieved=retriever.search(issue,10);const statutoryGap=Object.keys(statutory).includes(category);const supported=statutoryGap?[]:retrieved.filter(isVerified).slice(0,4);
  const rejected=retrieved.filter(x=>!isVerified(x));
  const relevant_laws:RelevantLaw[]=supported.map(r=>({source:r.chunk.title,provision:`Article ${r.chunk.article}`,title:r.chunk.heading.replace(/—.*$/,"").trim(),explanation:`This provision says, in substance: ${sentence(r.chunk.text)} Its relevance depends on the full facts and on whether the action involves the State or a public authority.`,relevance:relevance(r.score),citation_chunk_ids:[r.chunk.chunkId]}));
  const missing:string[]=[];if(/employer|fired|workplace/i.test(issue)&&!/(follow-up answer:[^\n]*(government|public authority|private)|(?:government|public authority|private) (?:employer|company|organisation))/i.test(issue))missing.push("Is your employer a government/public authority or a private organisation?");if(/police|arrest|detain|custody/i.test(issue)&&!/follow-up answer:/i.test(issue))missing.push("Have you been formally arrested, and were you told the grounds?");if(!/\b(assam|bihar|delhi|goa|gujarat|haryana|karnataka|kerala|maharashtra|odisha|punjab|rajasthan|tamil nadu|telangana|uttar pradesh|west bengal)\b/i.test(issue)&&statutoryGap&&!/follow-up answer:/i.test(issue))missing.push("Which State or Union Territory are you in?");
  return{emergency,emergency_guidance:emergency?["Move to a safer place if you can do so safely.","Contact a trusted person nearby.","Seek local emergency help. This database does not yet contain a verified emergency-resources directory, so no phone number is shown."]:undefined,issue_summary:`This appears to involve ${category}.`,issue_category:category,urgency:emergency?"urgent":/arrest|detain|threat|violence/i.test(issue)?"important":"normal",immediate_actions:emergency?[]:["Write down what happened, including dates, places and the people involved.","Preserve relevant messages, notices, photographs, receipts and screenshots.","Ask for important decisions, reasons or refusals in writing where it is safe to do so."],relevant_laws,next_steps:["Keep copies of all records in a safe place.","Consider a written representation that clearly states the facts and the outcome you seek.","If the matter is urgent, high-value or may affect your liberty or safety, seek help from a qualified lawyer or legal aid service."],missing_information:missing.slice(0,2),limitations:statutoryGap?`This appears primarily to be a ${category}. The current verified database contains only the Constitution of India, which does not provide the specific procedure or remedy for this issue. Relevant legislation and State-specific law would need to be consulted.`:"This guidance is limited to provisions retrieved from the Constitution of India. Other statutes, rules, judgments and State-specific procedures are not yet in the database.",professional_help_recommended:emergency||/arrest|detain|violence|fired/i.test(issue),...(debug?{debug:{classifiedIssue:category,searchQueries:[issue],retrievedChunks:retrieved.map(r=>({id:r.chunk.chunkId,article:r.chunk.article,score:+r.score.toFixed(4),keywordScore:+r.keywordScore.toFixed(4),semanticScore:+r.semanticScore.toFixed(4)})),provisionsSupplied:supported.map(r=>`Article ${r.chunk.article}`),finalCitations:supported.map(r=>r.chunk.chunkId),rejectedCitations:rejected.map(r=>r.chunk.chunkId)}}:{})}
}
